
 const dataAPI = [
    {
      AccountName: "Itexico",
      ActivityDate: "2022-06-06T09:35:04",
      ActivityID: 0,
      CategoryName: "Available",
      Comments: "string",
      EmployeeID: 0,
      ProjectColor: "blue",
      ProjectID: 0,
      ProjectName: "Delivery",
      StepID: 0,
      Task: "esto es un ticket",
      TypeID: 0,
      value: 5,
      activeInProject: false,
    },
    {
      AccountName: "Itexico",
      ActivityDate: "2022-06-06T09:35:04",
      ActivityID: 0,
      CategoryName: "Available",
      Comments: "string",
      EmployeeID: 0,
      ProjectColor: "blue",
      ProjectID: 0,
      ProjectName: "Delivery",
      StepID: 0,
      Task: "esto es un ticket",
      TypeID: 0,
      value: 5,
      activeInProject: false,
    },
    {
      AccountName: "Itexico",
      ActivityDate: "2022-06-06T09:35:04",
      ActivityID: 0,
      CategoryName: "Available",
      Comments: "string",
      EmployeeID: 0,
      ProjectColor: "blue",
      ProjectID: 0,
      ProjectName: "Delivery",
      StepID: 0,
      Task: "esto es un ticket",
      TypeID: 0,
      value: 5,
      activeInProject: false,
    },
    {
      AccountName: "Itexico",
      ActivityDate: "2022-06-06T09:35:04",
      ActivityID: 0,
      CategoryName: "Available",
      Comments: "string",
      EmployeeID: 0,
      ProjectColor: "blue",
      ProjectID: 0,
      ProjectName: "Delivery",
      StepID: 0,
      Task: "esto es un ticket",
      TypeID: 0,
      value: 5,
      activeInProject: false,
    },
    {
      AccountName: "Itexico",
      ActivityDate: "2022-06-06T09:35:04",
      ActivityID: 0,
      CategoryName: "Available",
      Comments: "string",
      EmployeeID: 0,
      ProjectColor: "blue",
      ProjectID: 0,
      ProjectName: "Delivery",
      StepID: 0,
      Task: "esto es un ticket",
      TypeID: 0,
      value: 5,
      activeInProject: false,
    },
  ];
export default dataAPI;